apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: bchen39/backend-app:tag
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/node-boilerplate"  # Use the MongoDB service DNS here
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
